# Triggered when tag is increased and has been pushed
name: 🚀 - Release workflow

on:
  push:
    tags:
      - '*'

jobs:
  main-jobs:
    name: 🔧 - Main jobs
    permissions:
      contents: read
    uses: ./.github/workflows/main.yml
    with:
      workflow: tags
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_ACCESS_KEY_SECRET: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      AWS_DRIVER_SEAT_ACCESS_KEY_ID: ${{ secrets.AWS_DRIVER_SEAT_ACCESS_KEY_ID }}
      AWS_DRIVER_SEAT_SECRET_ACCESS_KEY: ${{ secrets.AWS_DRIVER_SEAT_SECRET_ACCESS_KEY }}
