# Triggered when tag is increased and has been pushed
name: 🚀 - Release workflow
on:
  push:
    tags:
      - '*'

jobs:
  main-jobs:
    name: 🔧 - Main jobs
    uses: ./.github/workflows/main.yml
    with:
      workflow: tags
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_ACCESS_KEY_SECRET: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      EC2_GITHUB_TOKEN: ${{ secrets.EC2_GITHUB_TOKEN }}
